Command         ::= single-Command
                |   Command ; single-Command

single-Command  ::= "nothing"
                |   V-name := Expression
                |   Identifier (Actual-Parameters-Sequence)
                |   "let" Declaration "in" Command "end"
                |   "if" Expression "then" Command ("elsif" Expression "then" Command)*
                        "else" Command "end" | "choose" Expression "from" Cases "end"
                |   "choose" Expression "from" Cases "end"
                |   "loop" "while" Expression "do" Command "end"
                |   "loop" "until" Expression "do" Command "end"
                |   "loop" "do" Command ("while" Expression "end" | "until" Expression "end")
                |   "loop" "for" Identifier "from" Expression "to" Expression
                        ("do" command "end" | "while" Expression "do" Command "end" | "until" Expression "do" Command "end")
                
       