Program		::= (Token|Comment|Blank)*

Token			::= Integer-Literal|Character-Literal|Identifier|Operator|
		 	    array|begin|const|do|else|end|
			    func|if|in|let|of|proc|record|
			    then|type|var|while|
			    .|:|;|,|:=|~|(|)|[|]|{|}

Integer-Literal	::= Digit Digit* 

Character-Literal	::= 'Graphic'

Identifier		::= Letter(Letter|Digit)* 

Operator		::= Op-character Op-Character*

Comment		::= ! Graphic* end-of-line 

Blank			::= space|tab|end-of-line 

Graphic		::= Letter|Digit|Op-character|space|tab|.|:|;|,|
			    ~|(|)|[|]|{|}|_|||!|" ' "|`|' " ' |#|$	

Letter		::= a|b|c|d|e|f|g|h|i|j|k|l|m|
    n|o|p|q|r|s|t|u|v|w|x|y|z|
    			    A|B|C|D|E|F|G|H|I|J|K|L|M|
    N|O|P|Q|R|S|T|U|V|W|X|Y|Z

Digit			::= 0|1|2|3|4|5|6|7|8|9	

Op-character	::= +|-|*|/|=|<|>|\|&|@|%|^|?	


                
       